apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: inventory
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: inventory-api-config
    data:
      inventory-api-config.yaml: |
        storage:
          disable-persistence: false
        authn:
          allow-unauthenticated: true
        authz:
          kessel:
            insecure-client: true
            enable-oidc-auth: false
        log:
          level: "info"

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: psks
    data:
      psks.yaml: |
        "1234":
          tenant: "Example"
          principal: "user@example.com"
          is_reporter: true
          type: "REPORTER_TYPE_ACM"

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: resources-tarball
    binaryData:
        resources.tar.gz: H4sIAAAAAAAAA+1cW2/iOBTuM7/CYlYaadVCLoSseKM0nUZtoeLS2dnVKArBlOyEmHFCd9hq/vs61yYhCZSCO239qVLI8bHj5Fxqf3ZSqx8dHByBLEnekZclLnmMcMQ35KbE8bzMNY7IgWtwR0A6fNeOjpaOq2MAjnQ0xia0C/U2lb9S1Op4Bi1thhz3YJ6wrf0bstyUhSaxv8hJDWZ/GkjaH8MFwi7Ezp49YWv7NzlREHlif4kj6sz+FJBv/9nY3KMPPD3+pWZDZPangWL7G8iemne1lT63nnkNz8DNRqPQ/pIkxPFPHIDYnzgCsT+3lzvcgHdu/5OTkwqGDlpiA2ruagFbIHaISuQQmq3PSQHxior3y1noRnAKPgB3ZjqA/LkzCLxCgKb+76kJrUl0El2BnOguIJ7l6qbtBHWji3x0wER39coHIrF010S2tsBoAbFrQqdFxCdxQYtcUJvCCdbnC1IAAPyxwC3w8ABqujGvhSXg50+/0FmO/4GG2wJLB+LW75mWZrqj6ZMJuZrjYnP+n5lusBpKq8C0g9Z9ZWet8YWl262HB1+FCB0DmwvvCjWvgChXXtrS+SiO/1he+8dBz/L7TfHfkPh0/hc4SZBY/NPAQwWA6m+OMYNzvdoC1ZnrLlr1umfyk0BaQ/iuTgJq6p5wcj2Qfagee/W8fOFVQn4MBLLHmCUlXutE5ugutCzThZo58aSPNb3osu+q4OdxqLkca3Pd1u9I0gl0I9VYN1IlCcS8m7mOZtr30HYRXm2qoZMaYwv6Tl0FuZpE0deuYvh9aWLoNfj318ovG77PRjL+DTSfkzwY/zvw0vGzg/9oc/wLMpf+/y9wvMD+/1MBlfj/F+Fv/qChOP5zAy+nNhG95XCkjnT872vEn8am+OeaUmb8L/Eyi38qKBn7hwXxqLBFYu8EXJyqLPjeDmr1b3842gJZprE6FAG8A/9LMgDjf2ggZf8DEcA78L+8JDD700CB/XVjvj8f2IH/lcUmsz8NlNh/b8PBTfaXJDE7/+OaAhv/0UAO//voEFkCmHhFkgAmp4wAfuUEcEn8PxY8kwTaMP/jOamZ5X9lXmbxTwNU+J+J6ehjy+d0Akmi7hghC+p29TgqmMA4dLzyMzg1bUgyTJBIAof08o2xxBjarrUC0PZbBwiD6EokN2HkOEC3LEDsewddp1b1rxAzzfAeYtNd5fUpZKXiLkF7OY/5KF8yUG6Vvjr8oo26gxulo56rylmsnyzvDS+UfrLkqvc5eXqtnKmj66TkQv10kTzvkHbUTvuqGoq+Fj2pIXk80V0Bi/ywouwbRnH4AEqotthQ2YcU0m4v7a0M+0Yq/x+IANzM/zWz8z+hybH8TwNlY798ArDduWZ54M0gE/8HWQDcYf1PEFj8UwFb/3vfCOLfsEgYQHygBYAd+H8Cxv/RQNr+h1kA2IH/F0W2/58Kiuy/zwWAp8d/kxfY+z9UUGb/fU0HN/P/jbXxX4Pt/6SCAv4/dIjNCwAVtgDwqhcAyuI/UfKsWeCG+BdFWcjw/7wg8yz+aYDK/A/+IC5k61bkTRu3gUd6xDbu0tmNou9cjQZDpa8Nhu3haFBE1Ge01uj6vtI++5IUnLfVq3QTvfPzK7WrxPx8apkhuhMMdcen6Uvu+ttyDLV7En3mlpr2BOHdHs7l6FTRbpXuWa9f9GSSKmuPpX05SJ4q6VM1fdq7UbqDC/V8mBR+uix4YsFtbfccDAstJxrJr+4U4fmuftIbnWk3V+3hea9/XewnKa21B9LtdRVtdKMmZaftvnKtDNtXmlpUkKnR/jzI6nqirNZfo76ypucLM5rq6XXQcbVAntH3bH6r9odZfd+Cw3bnsrgg09Knzk1W1xNltLqjYbur/pnVjMQZ7dvBDXnqa3ceiTPavfhGct3MRhOYm1l0jPXVo8OYLpwn9fLTXliSk/zCEm9gVOrLoZ6xWG6jNodzhFfFXFqARJ11Xi3ZsbUu5F0sFn0Nf5EhTXAo5u7yMn9+js/Pl3mZMScH5qeO/CTBGMQkisZ/6IXn/2z/Hx2U2f8l5//s/W86eNr8H6Xn/4htAHyr83/0svN/kWP7/6iAzf/Z/J/N/9n8/9HmbP7P5v9s/v9ekB7/HWYD4A77/xoce/+LCtj+v/eNbPwf4gWATfwPTyZ7me9/NCQW/1RQyv0UvwAQHAf+scdeCHi9qNVt5JpT0/DJMO9jai68w/4Jff4/jv+mKDD+nwrK7L+v3cBP3v8rcGKDff+DCrazf0rnyd6wrf0lMhIIxv+iwLPvf1PBLvYvrFEwVdww/+OF7PqfyIsy2/9LBVTmf/EqYlhhB5a22xuq52qnPVR73cFWr8J7bXurj9HFj8HU/AEnwEXgY6q1j2CKcLASGd5x+ksBce9Nm/iKHc9iN91Epk9tsLTN70sIzAm0vQCCOLwwjPsIokscA2dpzIDuAB04EN+bBgS6YaCl7WZ6ZyFDtx4Zmx27Fih4/SAted0jJ17H/NaTPc4s527xTYG08cueaeEdVdjXBw6Fsvy/Lzbw6fyf2ODZ+79UwPi/943y+N/f/q+y+Od5eY3/l5os/mkgw/+lB/oJZyhkA1NDKRaWDAwMDAwMDAy/Ov4H2BfTwQB4AAA=

  - apiVersion: cloud.redhat.com/v1alpha1
    kind: ClowdApp
    metadata:
      name: kessel-inventory
    spec:
      envName: ${ENV_NAME}
      database:
        name: kessel-inventory
        version: 16
      optionalDependencies:
        - kessel-relations
      deployments:
        - name: api
          replicas: ${{REPLICAS}}
          podSpec:
            initContainers:
            - name: copy-resources
              image: busybox
              imagePullPolicy: Always
              command:
                - /bin/sh
                - "-c"
                - |
                  echo "Extracting resources from tarball..."
                  tar -xzf /mnt/resources/resources.tar.gz -C /data/schema/resources
                  echo "Extraction complete!"
              volumeMounts:
                - name: resources-tarball
                  mountPath: "/mnt/resources"
                - name: resource-volume
                  mountPath: "/data/schema/resources"
            - name: migration
              image: ${INVENTORY_IMAGE}:${IMAGE_TAG}
              imagePullPolicy: Always
              command: ["inventory-api"]
              args: ["migrate"]
              inheritEnv: true
            image: ${INVENTORY_IMAGE}:${IMAGE_TAG}
            imagePullPolicy: Always
            command: ["inventory-api"]
            args: ["serve"]
            livenessProbe:
              httpGet:
                path: /api/inventory/v1/livez
                port: 8000
            readinessProbe:
              httpGet:
                path: /api/inventory/v1/readyz
                port: 8000
            env:
            - name: CLOWDER_ENABLED
              value: "true"
            - name: INVENTORY_API_CONFIG
              value: "/inventory/inventory-api-config.yaml"
            - name: PGDATA
              value: /temp/data
            - name: RESOURCE_DIR
              value: "/data/schema/resources"
            volumeMounts:
                - name: config-volume
                  mountPath: "/inventory"
                - name: psks-volume
                  mountPath: /psks
                - name: resource-volume
                  mountPath: "/data/schema/resources"
                - name: resources-tarball
                  mountPath: "/mnt/resources"
            volumes:
              - name: config-volume
                configMap:
                  name: inventory-api-config
              - name: psks-volume
                configMap:
                  name: psks
              - name: resource-volume
                emptyDir: { }
              - name: resources-tarball
                configMap:
                  name: resources-tarball
          webServices:
            public:
              enabled: true
              apiPath: inventory

      testing:
        iqePlugin: kessel-inventory

parameters:
  - description: ClowdEnvironment name (ephemeral, stage, prod)
    name: ENV_NAME
    required: true
  - description: App Image
    name: INVENTORY_IMAGE
    value: quay.io/redhat-services-prod/project-kessel-tenant/kessel-inventory/inventory-api
  - description: Image Tag
    name: IMAGE_TAG
    required: true
    value: latest
  - description: Number of replicas
    name: REPLICAS
    value: "1"
